config/routes.rb
Rails.application.routes.draw do
  root'static_pages#home'
  
  get '/login',     to: 'static_pages#home'
  post '/login',    to: 'static_pages#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup',    to: 'users#new'
  get "music/:music_id"  => "music#show"
  post "music/:music_id" => "microposts#create"
  get "music/:music_id/edit" => "music_posts#edit"
  post "music/:music_id/edit" => "music_posts#update"
  
  resources :users 
  resources :microposts 
  get "/music_new", to: "music_posts#new"
  post "/music_new", to: "music_posts#create"
  get "/music_show", to: "music_posts#show"
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @musicposts = MusicPost.order(:music_name)
    end
    
  end

   
   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = "emailもしくはpasswordが間違っています"
      render "static_pages/home"
    end
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
 <body class="main_container">
 <div class ="container">
       <% if logged_in? &&  current_user.admin? %>
         <%= link_to("新規作成", music_new_path,{style: "color: white;"} ) %>
          <% end %>
  
  
       <% if logged_in? %>
         <% @musicposts.each do |musicpost| %>
        　 <div class="list-group">
             <a href="<%= "/music/#{musicpost.id}" %>" class="list-group-item list-group-item-action">
                    <h1 class="list-group-item-heading"><%= musicpost.music_name %> <span>></span></h1>
                   <h3 class="list-group-item-text" style= "display: inline;">one ok rock</h3>
             </a>
           </div>
         <% end %>
       <% else %>
           <div class= "container-fluid">
  
             <div class="visible-sm visible-xs">
            
                <h1 style="font-size: 500%;text-align: center;">Share o'clock</h1>
                <h2 style="margin-bottom: 200px; text-align: center;">ワンオクソングで時を共有しよう</h2>
            
              
         
                   <%= form_with(url: login_path, scope: :session, local: true) do |f| %>

                  <%= f.label :email,class: "big" %>
                  <%= f.email_field :email, class: 'form-control input big margin'  %>

                  <%= f.label :password,class: "big" %>
                  <%= f.password_field :password, class: 'form-control input big margin' %>

                   <%= f.submit "ログイン", class: "btn btn-primary input big margin" %>
                   <% end %>

                  <h1><%= link_to "新規登録はこちら", signup_path,{class: "link"} %></h1>
                
            </div>
           </div>
  
  
  
  
  
  <div class="visible-md visible-lg">
  <div class="row">
  <div class="col-md-6">
   <h1 style="font-size: 400%;font-weight: 900;">Share o'clock </h1>
   <h2>ワンオクソングで時を共有しよう</h2>
  </div>
  <div class="col-md-6">
    <h1>Log in</h1>
    <%= form_with(url: login_path, scope: :session, local: true) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "ログイン", class: "btn btn-primary", style: "width: 100%; margin-top: 20px;" %>
    <% end %>

    <h3> <%= link_to "新規登録はこちら", signup_path,{class: "link"} %></h3>
  </div>
  </div>
  </div>
<% end %>
</div>
</body>