config/routes.rb
Rails.application.routes.draw do
  root'static_pages#home'
  
  get '/login',     to: 'static_pages#home'
  post '/login',    to: 'static_pages#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup',    to: 'users#new'
  get "music/:music_id"  => "music#show"
  post "music/:music_id" => "microposts#create"
  get "music/:music_id/edit" => "music_posts#edit"
  post "music/:music_id/edit" => "music_posts#update"
  
  resources :users 
  resources :microposts 
  get "/music_new", to: "music_posts#new"
  post "/music_new", to: "music_posts#create"
  get "/music_show", to: "music_posts#show"
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="visible-sm visible-xs">
<div class="well well-lg f-container1 fixed">
 <% if logged_in? %>
  <div class="f-item1"><%= link_to "ホーム", root_path %></div>
  <div class="f-item1"><%= link_to "自分の投稿", user_path(current_user)%></div>
  <div  class="f-item1"><%= link_to "みんなの投稿", "/microposts/show" %></div>
   <div  class="f-item1"><%= link_to "ログアウト", logout_path, method: :delete %></div>
   <div  class="f-item1"><%= link_to "設定", edit_user_path(current_user) %></div>
   <% else %>
   <div  class="f-item1"><%= link_to "ホーム", root_path %></div>
   <% end %>
 </div>
 </div>
 
 
 <div class="visible-lg visible-md ">
<div class="well well-lg f-container2 fixed">
 <% if logged_in? %>
  <div class="f-item2"><%= link_to "ホーム", root_path %></div>
  <div class="f-item2"><%= link_to "自分の投稿一覧", user_path(current_user)%></div>
  <div  class="f-item2"><%= link_to "みんなの投稿", "/microposts/show" %></div>
   <div  class="f-item2"><%= link_to "ログアウト", logout_path, method: :delete %></div>
   <div  class="f-item2"><%= link_to "設定", edit_user_path(current_user) %></div>
   <% else %>
   <div  class="f-item2"><%= link_to "ホーム", root_path %></div>
   <% end %>
 </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share o'clock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" >
  </head>

  <body class ="main_container main">
 <%= render 'layouts/header' %>
      <div style="padding-top: 100px;">
      <div class= "row">
        <div class = "col-xs-6 col-xs-offset-3">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>
      </div>
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/header.html.erb
  <% if logged_in? %>
        <li><%= link_to "ホーム", root_path %></h1>  
        <li><%= link_to "自分の投稿一覧", user_path(current_user) %></li> 
        <li><%= link_to "みんなの投稿", "/microposts/show" %></li>  
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <li><%= link_to "設定", edit_user_path(current_user) %></li>
         <% else%>
        <li> <%= link_to "ホーム", root_path %></li> 　
          <% end %>